[toolchain]

[features]
seeds = false
skip-lint = false

[programs.mainnet]
madscape = "moonKi1FYsaWQnmqjvnLTXZbDkwpEzzCEXtnfo2bJHC"

[programs.devnet]
madscape = "moonKi1FYsaWQnmqjvnLTXZbDkwpEzzCEXtnfo2bJHC"

[programs.localnet]
madscape = "moonKi1FYsaWQnmqjvnLTXZbDkwpEzzCEXtnfo2bJHC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/moonscape.json"

[scripts]
approve_mint = "yarn run ts-node scripts/approveMint.ts"
create_release_authority = "yarn run ts-node scripts/createReleaseAuthority.ts"
fetch_release_authority = "yarn run ts-node scripts/fetchReleaseAuthority.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

#solana program deploy --program-id target/deploy/madscape-keypair.json target/deploy/madscape.so --with-compute-unit-price 10000 --use-rpc --max-sign-attempts 100
